# Generated by Django 3.2.5 on 2022-03-08 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='media/images')),
                ('pdf_file', models.FileField(upload_to='media/pdf')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readingApp.genre')),
            ],
        ),
    ]
